### ISSUE TITLE
Inclusion in to TechDraw wb?

### ISSUE THREAD

**Issue by luzpaz** [JohnHyslop/FreeCAD-SVG-TechDraw-Symbols#1]
CC @wandererfan

**Comment by WandererFan** [comment]
There are at least a couple of duplicates with what is in
Mod/TechDraw/Symbols.  If the duplicates are sorted out then we could
definitely add these.

**Comment by luzpaz** [comment]
@JohnHyslop would you be interested in sorting out the differences and making a Pull Request?

**Comment by JohnHyslop** [comment]
Hi Luzpuz/WandererFan
I will sort out if you let me know what ones to remove, as for a Pull Request I'm a bit of a noob on gethub and not sure how to do that but happy to do if I know how.. 
Are you back WandererFan I haven't been on the forum for quite a while?
Cheers
John

**Comment by luzpaz** [comment]
Forum thread: https://forum.freecadweb.org/viewtopic.php?f=35&t=65862

**Comment by JohnHyslop** [comment]
Hi luzpaz
I'll have a look today and try and figure out the duplicates..
would yourself or WandererFan be happy with the naming suggestion in the posted topic?
This >> "TechDraw_CommandNameAllOneWord i.e. TechDraw_Dimension"?
Also I might need some guidance regarding forking , I have no idea how to do that ...

Cheers
John Hyslop [thebighaggis]  
PS BTW In Melbourne Australia It's 9.30am so hopefully I can get this moving today..

**Comment by JohnHyslop** [comment]
Hi
I cannot fork because I'm not a member of any organizations? could you suggest one or how I can join please?
Also I had a look at some symbols that had the prefix "TechDraw_"  and they all seem to be Icons?
the ones I've made are to be used as symbols in the drawing itself.. I think if they were mixed up it would lead to confusion.
If someone could point me in the right direction that would be good as I'm not familiar with a lot of the terms used in github 
Cheers
John

**Comment by luzpaz** [comment]
@JohnHyslop all things git related to FreeCAD you can find at https://wiki.freecad.org/github

The abstract version: you'll need to 'clone' the FreeCAD github repo. You create your own branch. Make changes to that branch. Then you make Pull Request back to the FreeCAD github repo asking to merge those changes of said branch.

**Comment by JohnHyslop** [comment]
1st I must apologise, This is very new territory for me , I have absolutely no idea what I'm doing..
I've downloaded visual studio code , cloned FreeCAD repo added a folder in TechDraw-Symbols-misc
When I type get status it shows all the new files "I manually copied into folder then used git add *.svg"
... I removed duplicates from my repo "3 surface symbols" 
Any help would be appreciated .. 
Cheers
John

**Comment by luzpaz** [comment]
No worries. git is a PITA but it starts making sense when you use it more. The skill starts translating to other projects so it's worth your time to grok :smile: 

Lets review: you should have a: 

- [ ] created your own github fork of it called 'origin' (AKA https://github.com/JohnHyslop/FreeCAD) by pushing the 'Fork' button on [Github](https://github.com/FreeCAD/FreeCAD) :x:
- [ ] cloned your repository of 'origin' FreeCAD (AKA `git clone https://github.com/JohnHyslop/FreeCAD`) :x: 
- [ ] added your remote github fork as 'upstream' to your local repository (`git remote add upstream https://github.com/FreeCAD/FreeCAD`) :x:
- [ ] created a branch off of the FreeCAD 'master' branch (lets assume 'TD-symbols' so `git checkout -b TD-symbols`) :x: 
- [x] made the necessary changes (moved symbols in to a new directory) :heavy_check_mark: 
- [x] staged the changed (`git add`)
- [ ] committed changes to a commit (something line `git commit -m "TD: Adding more TechDraw svg symbols" -m "Per the discussion in https://github.com/JohnHyslop/FreeCAD-SVG-TechDraw-Symbols/issues/1"`)
- [ ] pushed the changes to your github (`git push origin TD-symbols`)
- [ ] Browsed https://github.com/FreeCAD/FreeCAD and clicked the 'Make a PR' button
- [ ] Chose the correct branch ('TD-symbols') on your repo (https://github.com/JohnHyslop/FreeCAD) to be added to the 'master' branch on https://github.com/FreeCAD/FreeCAD
- [ ] Fill out the PR summary
- [ ] x-post the PR URL back to this ticket for us to review

**Comment by JohnHyslop** [comment]
Thank you very much luzpaz, I hope it all went through ok. :)
I would definitely not of been able to do this without your help..
Link to request / ticket? below.
https://github.com/FreeCAD/FreeCAD/pull/5506

Cheers
John

**Comment by luzpaz** [comment]
Mission accomplished! Well done!
